/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace HexMapScene_UI
{
    partial class HexMapTestPanel : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static HexMapTestPanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btTextQuest = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifQuestIndex = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btClose = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(btTextQuest);
            SubscribeOnChanged(ifQuestIndex);
            SubscribeOnChanged(btClose);
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}