/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace HexMapScene_UI
{
    partial class TextQuestVariant : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static TextQuestVariant Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton bt = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(bt);
            SubscribeOnChanged(tx);
        }
        ///<summary>Data</summary>
        public Model.QuestVariant variant{ get; private set; }
        
        [VisibleInGraph(false)]
        public void Build(Model.QuestVariant variant)
        {
            this.variant = variant;
            OnBuildSafe(true);
        }
        
        public override BaseView Clone()
        {
            var clone = (TextQuestVariant)base.Clone();
            clone.variant = variant;
            return clone;
        }
    }
}