/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace SceneSelection_UI
{
    partial class SelectScenePanel : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static SelectScenePanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btHub = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btTextQuest = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifQuestIndex = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btHexMap = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btExit = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(btHub);
            SubscribeOnChanged(btTextQuest);
            SubscribeOnChanged(ifQuestIndex);
            SubscribeOnChanged(btHexMap);
            SubscribeOnChanged(btExit);
            Subscribe(btExit, () => UIManager.CloseApp());
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}