/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace Hub_UI
{
    partial class BackgroundMenu : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static BackgroundMenu Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btBuy = default;
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btMission = default;
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btShipUpgrade = default;
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btSettings = default;
        [AutoGenerated, SerializeField, HideInInspector] BuyPanel BuyPanel = default;
        [AutoGenerated, SerializeField, HideInInspector] PlayerInfoPanel PlayerInfoPanel = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(btBuy);
            SubscribeOnChanged(btMission);
            SubscribeOnChanged(btShipUpgrade);
            SubscribeOnChanged(btSettings);
            SubscribeOnChanged(BuyPanel);
            SubscribeOnChanged(PlayerInfoPanel);
            Subscribe(btBuy, () => BuyPanel.BuildAndShow(OwnerForChild));
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}