/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace Hub_UI
{
    partial class BuyPanel : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static BuyPanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.UnitButton pnUnit0 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.UnitButton pnUnit1 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.UnitButton pnUnit2 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.UnitButton pnUnit3 = default;
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btClose = default;
        [AutoGenerated, SerializeField, HideInInspector] BuyUnitPanel BuyUnitPanel = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(pnUnit0);
            SubscribeOnChanged(pnUnit1);
            SubscribeOnChanged(pnUnit2);
            SubscribeOnChanged(pnUnit3);
            SubscribeOnChanged(btClose);
            SubscribeOnChanged(BuyUnitPanel);
            Subscribe(btClose, () => this.Close());
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}