/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace Hub_UI
{
    partial class ItemButton : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static ItemButton Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton bt = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Image imCountCircle = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txCount = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(bt);
            SubscribeOnChanged(imCountCircle);
            SubscribeOnChanged(txCount);
        }
        ///<summary>Data</summary>
        public Model.IItem item{ get; private set; }
        public int count{ get; private set; }
        public bool isActive{ get; private set; }
        
        [VisibleInGraph(false)]
        public void Build(Model.IItem item, int count, bool isActive)
        {
            this.item = item;
            this.count = count;
            this.isActive = isActive;
            OnBuildSafe(true);
        }
        
        public override BaseView Clone()
        {
            var clone = (ItemButton)base.Clone();
            clone.item = item;
            clone.count = count;
            clone.isActive = isActive;
            return clone;
        }
    }
}