/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace Hub_UI
{
    partial class ItemInfo : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static ItemInfo Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txName = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Image imIcon = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txRarity = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txInStorage = default;
        [AutoGenerated, SerializeField, HideInInspector] StatLine StatLine = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(txName);
            SubscribeOnChanged(imIcon);
            SubscribeOnChanged(txRarity);
            SubscribeOnChanged(txInStorage);
            SubscribeOnChanged(StatLine);
        }
        ///<summary>Data</summary>
        public Model.IItem item{ get; private set; }
        
        [VisibleInGraph(false)]
        public void Build(Model.IItem item)
        {
            this.item = item;
            OnBuildSafe(true);
        }
        
        public override BaseView Clone()
        {
            var clone = (ItemInfo)base.Clone();
            clone.item = item;
            return clone;
        }
    }
}