/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace Hub_UI
{
    partial class StartMissionPanel : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static StartMissionPanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btClose = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.UnitSlot pnUnitSlot0 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.UnitSlot pnUnitSlot1 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.UnitSlot pnUnitSlot2 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.UnitSlot pnUnitSlot3 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.SupplyBuy pnSupplyBuy0 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.SupplyBuy pnSupplyBuy1 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.SupplyBuy pnSupplyBuy2 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.SupplyBuy pnSupplyBuy3 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Toggle tgShort = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Toggle tgMiddle = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Toggle tgLong = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Toggle tgSpecial = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.RectTransform pnPrizes = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txDescription = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txPrizeDesc = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.ItemIcon pnItemIcon0 = default;
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.ItemIcon pnItemIcon1 = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txError = default;
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btStart = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(btClose);
            SubscribeOnChanged(pnUnitSlot0);
            SubscribeOnChanged(pnUnitSlot1);
            SubscribeOnChanged(pnUnitSlot2);
            SubscribeOnChanged(pnUnitSlot3);
            SubscribeOnChanged(pnSupplyBuy0);
            SubscribeOnChanged(pnSupplyBuy1);
            SubscribeOnChanged(pnSupplyBuy2);
            SubscribeOnChanged(pnSupplyBuy3);
            SubscribeOnChanged(tgShort);
            SubscribeOnChanged(tgMiddle);
            SubscribeOnChanged(tgLong);
            SubscribeOnChanged(tgSpecial);
            SubscribeOnChanged(pnPrizes);
            SubscribeOnChanged(txDescription);
            SubscribeOnChanged(txPrizeDesc);
            SubscribeOnChanged(pnItemIcon0);
            SubscribeOnChanged(pnItemIcon1);
            SubscribeOnChanged(txError);
            SubscribeOnChanged(btStart);
            Subscribe(btClose, () => this.Close());
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}