/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace Hub_UI
{
    partial class StoragePanel : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static StoragePanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] Hub_UI.SellSlot pnSellSlot = default;
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btSortByType = default;
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btSortByPrice = default;
        [AutoGenerated, SerializeField, HideInInspector] ItemButton ItemButton = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(pnSellSlot);
            SubscribeOnChanged(btSortByType);
            SubscribeOnChanged(btSortByPrice);
            SubscribeOnChanged(ItemButton);
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}