/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace Hub_UI
{
    partial class SupplyBuy : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static SupplyBuy Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txPrice = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txCount = default;
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btAdd = default;
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton btSub = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(txPrice);
            SubscribeOnChanged(txCount);
            SubscribeOnChanged(btAdd);
            SubscribeOnChanged(btSub);
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}