/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace Hub_UI
{
    partial class UnitInfo : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static UnitInfo Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txName = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Image imIcon = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txLevel = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txExp = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txHealth = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txenShield = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txSoul = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txFarFight = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txNearFight = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txAvoidance = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txCrit = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txMoving = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Image imTrait0 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Image imTrait1 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Image imTrait2 = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(txName);
            SubscribeOnChanged(imIcon);
            SubscribeOnChanged(txLevel);
            SubscribeOnChanged(txExp);
            SubscribeOnChanged(txHealth);
            SubscribeOnChanged(txenShield);
            SubscribeOnChanged(txSoul);
            SubscribeOnChanged(txFarFight);
            SubscribeOnChanged(txNearFight);
            SubscribeOnChanged(txAvoidance);
            SubscribeOnChanged(txCrit);
            SubscribeOnChanged(txMoving);
            SubscribeOnChanged(imTrait0);
            SubscribeOnChanged(imTrait1);
            SubscribeOnChanged(imTrait2);
        }
        ///<summary>Data</summary>
        public Unit unit{ get; private set; }
        
        [VisibleInGraph(false)]
        public void Build(Unit unit)
        {
            this.unit = unit;
            OnBuildSafe(true);
        }
        
        public override BaseView Clone()
        {
            var clone = (UnitInfo)base.Clone();
            clone.unit = unit;
            return clone;
        }
    }
}