/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace Hub_UI
{
    partial class UnitButton : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static UnitButton Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] OutlineButton bt = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI txName = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(bt);
            SubscribeOnChanged(txName);
        }
        ///<summary>Data</summary>
        public Unit unit{ get; private set; }
        public bool isActive{ get; private set; }
        
        [VisibleInGraph(false)]
        public void Build(Unit unit, bool isActive)
        {
            this.unit = unit;
            this.isActive = isActive;
            OnBuildSafe(true);
        }
        
        public override BaseView Clone()
        {
            var clone = (UnitButton)base.Clone();
            clone.unit = unit;
            clone.isActive = isActive;
            return clone;
        }
    }
}