namespace Model
{
    partial class Database
    {
        static partial void UnitNames()
        {
            AddName("Алан");
            AddName("Морган");
            AddName("Алекс");
            AddName("Никки");
            AddName("Алексис");
            AddName("Ноэль");
            AddName("Блэр");
            AddName("Оливер");
            AddName("Бобби");
            AddName("Робби");
            AddName("Вайолет");
            AddName("Робин");
            AddName("Вэл");
            AddName("Рэй");
            AddName("Гейл");
            AddName("Саймон");
            AddName("Даррен");
            AddName("Сидни");
            AddName("Дарси");
            AddName("Стивен");
            AddName("Джеймс");
            AddName("Сэм");
            AddName("Джеки");
            AddName("Тейлор");
            AddName("Диллон");
            AddName("Тео");
            AddName("Дэнни");
            AddName("Тони");
            AddName("Каллум");
            AddName("Уэйн");
            AddName("Кейси");
            AddName("Финн");
            AddName("Кори");
            AddName("Хью");
            AddName("Крис");
            AddName("Чарли");
            AddName("Лесли");
            AddName("Шеннон");
            AddName("Ли");
            AddName("Эдди");
            AddName("Макс");
            AddName("Элис");
            AddName("Мел");
            AddName("Энди");
            AddName("Меттью");
            AddName("Эшли");
            AddName("Микки");
        }
    }
}